name: selforder
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/cafe.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/cafe.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/cafe.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/cafe.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/cafe.png
    - images/hot-pot.png
    - images/drink.png
    - images/cookie.png
    - images/Americano.png
    - images/Churros_result.png
    - images/Nasi Goreng_result.png
    - images/
    - assets/icons/